# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bobby Steinbach | Developer, Entrepreneur, Lover of Pugs
email: me@iambob.me
description: > # this means to ignore newlines until "baseurl:"
  Hey there! I'm a developer, leader, and entrepreneur currently working out of NYC. Drop me a line, I'd love to hear from you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.iambob.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: steinbachr
github_username:  steinbachr

collections:
  work:
    output: false
  woodworking:
    output: false

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
